import { Context, OperationType, Service, TodoistResponse } from '../types/index';
import {
	// Task operations
	CloseHandler,
	CreateHandler,
	DeleteHandler,
	GetAllHandler,
	GetHandler,
	MoveHandler,
	ReopenHandler,
	SyncHandler,
	UpdateHandler,
	// Project operations
	GetAllProjects,
	GetProject,
	DeleteProject,
	CreateProject,
	UpdateProject,
	ArchiveProject,
	UnarchiveProject,
	GetAllCollaborators,
	GetOrCreateProject,
	// Section operations
	CreateSection,
	DeleteSection,
	GetAllSections,
	GetSection,
	UpdateSection,
	// Comment operations
	CreateComment,
	DeleteComment,
	GetAllComments,
	GetComment,
	UpdateComment,
	CreatePersonalLabel,
	DeletePersonalLabel,
	GetAllPersonalLabels,
	GetAllSharedLabels,
	GetPersonalLabel,
	RemoveSharedLabels,
	RenameSharedLabels,
	UpdatePersonalLabel,
	// Task operations
	GetOrCreateTask,
	GetOrCreatePersonalLabel,
	GetOrCreateSection,
} from '../operations';

export class TodoistCustomService implements Service {
	async execute(
		ctx: Context,
		operation: OperationType,
		itemIndex: number,
	): Promise<TodoistResponse> {
		return await this.handlers[operation].handleOperation(ctx, itemIndex);
	}

	private handlers = {
		create: new CreateHandler(),
		close: new CloseHandler(),
		delete: new DeleteHandler(),
		get: new GetHandler(),
		getAll: new GetAllHandler(),
		reopen: new ReopenHandler(),
		update: new UpdateHandler(),
		move: new MoveHandler(),
		sync: new SyncHandler(),
		getOrCreateTask: new GetOrCreateTask(new CreateHandler()),
		getAllProjects: new GetAllProjects(),
		createProject: new CreateProject(),
		getProject: new GetProject(),
		deleteProject: new DeleteProject(),
		updateProject: new UpdateProject(),
		archiveProject: new ArchiveProject(),
		unarchiveProject: new UnarchiveProject(),
		getProjectCollaborators: new GetAllCollaborators(),
		getOrCreateProject: new GetOrCreateProject(new CreateProject()),
		getAllSections: new GetAllSections(),
		createSection: new CreateSection(),
		getOrCreateSection: new GetOrCreateSection(new CreateSection()),
		getSection: new GetSection(),
		updateSection: new UpdateSection(),
		deleteSection: new DeleteSection(),
		getAllComments: new GetAllComments(),
		createComment: new CreateComment(),
		getComment: new GetComment(),
		updateComment: new UpdateComment(),
		deleteComment: new DeleteComment(),
		getAllPersonalLabels: new GetAllPersonalLabels(),
		createPersonalLabel: new CreatePersonalLabel(),
		getPersonalLabel: new GetPersonalLabel(),
		updatePersonalLabel: new UpdatePersonalLabel(),
		deletePersonalLabel: new DeletePersonalLabel(),
		getOrCreatePersonalLabel: new GetOrCreatePersonalLabel(new CreatePersonalLabel()),
		getAllSharedLabels: new GetAllSharedLabels(),
		renameSharedLabels: new RenameSharedLabels(),
		removeSharedLabels: new RemoveSharedLabels(),
	};
}
